# Generated by Django 5.2.8 on 2025-11-25 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_mailing_datetime_end_emailstatistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 26, 9, 53, 25, 703931, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
