# Generated by Django 5.2.8 on 2025-11-27 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_alter_clients_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 28, 14, 0, 39, 168631, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создана"),
                    ("started", "запущена"),
                    ("completed", "завершена"),
                    ("closed", "отключена"),
                ],
                default="created",
                max_length=10,
            ),
        ),
    ]
