# Generated by Django 5.2.8 on 2025-11-29 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_mailing_datetime_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Укажите город'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 14, 59, 12, 933414, tzinfo=datetime.timezone.utc)),
        ),
    ]
