# Generated by Django 5.2.8 on 2025-12-04 15:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_mailing_datetime_end'),
        ('products', '0003_product_description_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 5, 15, 53, 20, 112091, tzinfo=datetime.timezone.utc)),
        ),
    ]
