# Generated by Django 5.2.12 on 2026-03-31 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0013_message_product_alter_mailing_datetime_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Укажите город"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 1, 13, 7, 26, 571425, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
