# Generated by Django 5.2.12 on 2026-03-31 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0014_alter_clients_location_alter_mailing_datetime_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 1, 13, 10, 44, 757559, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
