# Generated by Django 5.2.12 on 2026-03-31 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0015_alter_mailing_datetime_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 1, 13, 28, 58, 569995, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
