# Generated by Django 5.2.12 on 2026-04-02 10:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0016_alter_mailing_datetime_end"),
        ("products", "0003_product_description_alter_product_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 3, 10, 41, 33, 962477, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="OfferFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название файла"),
                ),
                (
                    "file",
                    models.FileField(upload_to="price_files/", verbose_name="Файл"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель файла",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        to="products.product", verbose_name="Выбранные продукты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сгенерированный файл",
                "verbose_name_plural": "Сгенерированные файлы",
            },
        ),
    ]
