# Generated by Django 5.2.12 on 2026-04-02 12:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0017_alter_mailing_datetime_end_offerfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="offer_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.offerfile",
                verbose_name="Прикрепленный файл",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 3, 12, 46, 24, 732759, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
