# Generated by Django 5.2.12 on 2026-04-03 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0018_message_offer_file_alter_mailing_datetime_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 4, 12, 37, 12, 390885, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
