# Generated by Django 5.2.12 on 2026-04-26 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0019_alter_mailing_datetime_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 27, 15, 45, 16, 807209, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
