# Generated by Django 5.2.12 on 2026-04-26 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0020_alter_mailing_datetime_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 27, 18, 25, 54, 320558, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
