# Generated by Django 5.2.12 on 2026-04-26 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0021_clients_phone_number_alter_mailing_datetime_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 27, 18, 30, 23, 373487, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
