# Generated by Django 5.2.12 on 2026-04-26 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0022_alter_clients_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="clients",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя клиента"),
        ),
        migrations.AlterField(
            model_name="clients",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 27, 20, 48, 20, 312992, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
