# Generated by Django 5.2.12 on 2026-04-26 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0023_alter_clients_comment_alter_clients_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 27, 20, 49, 19, 787201, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
