# Generated by Django 5.2.12 on 2026-04-27 09:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0024_alter_mailing_datetime_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="offerfile",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offer_files",
                to="clients.clients",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 28, 9, 49, 17, 215290, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
