# Generated by Django 5.2.12 on 2026-04-27 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0025_offerfile_client_alter_mailing_datetime_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 28, 17, 13, 15, 681174, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
