# Generated by Django 5.2.12 on 2026-04-28 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0026_alter_mailing_datetime_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 29, 15, 49, 5, 861709, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
