# Generated by Django 5.2.12 on 2026-05-05 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0030_alter_mailing_datetime_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 5, 6, 13, 18, 41, 547976, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
