# Generated by Django 5.2.12 on 2026-05-07 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0031_alter_mailing_datetime_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 5, 8, 14, 52, 41, 72642, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
