# Generated by Django 5.2.12 on 2026-05-11 08:53

import clients.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0032_alter_mailing_datetime_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="datetime_end",
            field=models.DateTimeField(default=clients.models.get_default_end_date),
        ),
    ]
