# Generated by Django 5.2.12 on 2026-05-11 09:06

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0034_alter_clients_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="RU", verbose_name="Номер телефона"
            ),
        ),
    ]
