# Generated by Django 5.2.12 on 2026-05-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0036_city_alter_clients_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="offerfile",
            name="is_sent",
            field=models.BooleanField(default=False, verbose_name="Отправлено"),
        ),
    ]
