# Generated by Django 5.2.12 on 2026-05-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0037_offerfile_is_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offerfile",
            name="client",
        ),
        migrations.RemoveField(
            model_name="offerfile",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="offerfile",
            name="products",
        ),
    ]
