# Generated by Django 5.2.12 on 2026-05-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0037_offerfile_is_sent"),
        ("documents", "0006_move_offerfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="offer_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.offerfile",
                verbose_name="Прикрепленный файл",
            ),
        ),
        migrations.AlterModelOptions(
            name="clients",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="message",
            name="header",
            field=models.CharField(max_length=200, verbose_name="Заголовок сообщения"),
        ),
        migrations.DeleteModel(
            name="OfferFile",
        ),
    ]
