# Generated by Django 5.2.12 on 2026-05-14 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients",
            "0038_remove_offerfile_client_remove_offerfile_created_by_and_more",
        ),
        ("documents", "0006_offerfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="offer_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.offerfile",
                verbose_name="Прикрепленный файл",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="message",
            name="header",
            field=models.CharField(max_length=200, verbose_name="Заголовок сообщения"),
        ),
        migrations.DeleteModel(
            name="OfferFile",
        ),
    ]
