# Generated by Django 5.2.12 on 2026-05-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0038_remove_offerfile_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clients",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="message",
            name="header",
            field=models.CharField(max_length=200, verbose_name="Заголовок сообщения"),
        ),
    ]
