# Generated by Django 5.2.12 on 2026-04-28 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("products", "0005_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.product",
            ),
        ),
    ]
