# Generated by Django 5.2.12 on 2026-04-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_invoiceitem_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название шаблона"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="invoice_templates/", verbose_name="Файл шаблона"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Шаблон счёта",
                "verbose_name_plural": "Шаблоны счетов",
            },
        ),
    ]
