# Generated by Django 5.2.12 on 2026-05-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_invoicetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
