# Generated by Django 5.2.12 on 2026-05-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_invoice_is_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
