# Generated by Django 5.2.12 on 2026-05-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_invoice_number"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="OfferFile",
                    fields=[
                    ],
                    options={
                        "db_table": "clients_offerfile",
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
