# Generated by Django 5.2.12 on 2026-05-16 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0038_alter_message_offer_file_alter_clients_options_and_more"),
        ("documents", "0006_move_offerfile"),
        ("products", "0005_product_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offerfile",
            options={
                "verbose_name": "Сгенерированный файл",
                "verbose_name_plural": "Сгенерированные файлы",
            },
        ),
        migrations.AddField(
            model_name="offerfile",
            name="products",
            field=models.ManyToManyField(
                to="products.product", verbose_name="Выбранные продукты"
            ),
        ),
        migrations.AlterField(
            model_name="offerfile",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offer_files",
                to="clients.clients",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="offerfile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="offerfile",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель файла",
            ),
        ),
        migrations.AlterField(
            model_name="offerfile",
            name="file",
            field=models.FileField(upload_to="price_files/", verbose_name="Файл"),
        ),
        migrations.AlterField(
            model_name="offerfile",
            name="is_sent",
            field=models.BooleanField(default=False, verbose_name="Отправлено"),
        ),
        migrations.AlterField(
            model_name="offerfile",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название файла"),
        ),
    ]
