# Generated by Django 5.2.8 on 2025-11-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание'),
        ),
    ]
